#!/bin/bash
python main.py --dataset 'celeba' \
--partition_method 'noniid-pathological' \
--batch_size 32 \
--lr 2e-5 \
--epochs 1 \
--client_num_in_total 20 --frac 0.2 \
--sample_every 100 \
--fid_freq 100 \
--comm_round 5000 \
--seed 2023 \
--save \
--calculate_fid \
--calculate_is \
--gradient_accumulate_every 2 \
--aggr_freq 5 \
--balance_agg_a 20000 \
--num_edge_servers 2 \
--train_scratch \
--pruning_ratio 0.3 \
--tqdm